<?php echo $this->form()->openTag($form);?>
    <div class="form-messages"><?php echo  $this->formErrors; ?></div>
    <?php echo  $this->originalFields; ?>
    <?php echo $this->formInput($form->get('choice_id')); ?>
    <?php echo $this->formInput($form->get('option_id')); ?>
    <?php echo $this->formInput($form->get('product_id')); ?>

    <div class="row">
        <div class="span3">
            <?php echo $this->speckCatalogManagerFormRow($form->get('override_name')); ?>
        </div>
        <div class="span2">
        </div>
        <div class="span2">
        </div>
    </div>

</form>
