<?php echo $this->form()->openTag($form);?>
    <div class="form-messages"><?php echo  $this->formErrors; ?></div>
    <?php echo  $this->originalFields; ?>
    <?php echo  $this->formRow($form->get('spec_id')); ?>
    <?php echo  $this->formRow($form->get('product_id')); ?>

    <div class="row">
        <div class="span3">
            <?php echo  $this->speckCatalogManagerFormRow($form->get('label')->setAttribute('class', 'span3')); ?>
        </div>
        <div class="span3">
            <?php echo  $this->speckCatalogManagerFormRow($form->get('value')->setAttribute('class', 'span3')); ?>
        </div>
    </div>

</form>
