<?php $pdir = '/speck-catalog/catalog/partial/'; ?>
<?php foreach ($option->getChoices() as $choice): ?>
    <input name="product_branch[<?php echo $option->getOptionId();?>][<?php echo $choice->getChoiceId(); ?>]" value="<?php echo $choice->getChoiceId();?>" type="radio">&nbsp;<?php echo $choice->__toString();?>
    <?php if($choice->has('options')) : ?>
        <?php foreach($choice->getOptions() as $option) : ?>
            <br/><?php echo $this->partial($pdir . 'option.phtml', array('option' => $option)); ?>
        <?php endforeach; ?>
    <?php else: ?>
        <br/>
    <?php endif; ?>
<?php endforeach; ?>
