<?php
$pdir = '/speck-catalog/product/';
?>
<h2><?php echo $product->getName();?></h2>

<form id="product-for-cart" method="POST" action="/cart/add-product">
<input type="hidden" name="product_id" value="<?php echo $product->getProductId();?>"/>

<div class="row">
    <div class="span3 bordered-table">
        <?php if($product->has('image')): ?>
            <?php $image = $product->getImage(); ?>
            <img src="<?php echo $this->speckCatalogImage()->product($image);?>" width="200" height="200" />
        <?php else: ?>
            asdf
            <img src="nopic.jpg" width="200" height="200"/>
        <?php endif; ?>
    </div>
    <div class="span8 well">
        <?php if($product->has('manufacturer')): ?>
            <?php echo $product->getManufacturer()->getName();?>
            <hr/>
        <?php endif; ?>
        <?php if(!$product->has('options')) : ?>
            <input type="text" name="quantity" value="1">
            <input type="submit" value="Add To Cart"/>
            <hr/>
        <?php endif; ?>
        <?php echo $product->getDescription(); ?>
    </div>
</div>

<?php if( $product->has('options') || $product->has('specs') || $product->has('documents') ): ?>
    <div class="tabbable" class="row">
        <ul class="nav nav-tabs">
            <?php if($product->has('options')) : ?>
                <li><a href="#options" data-toggle="tab">Configure and Buy</a></li>
            <?php endif; ?>
            <?php if($product->has('specs')) : ?>
                <li><a href="#specs" data-toggle="tab">Specs</a></li>
            <?php endif; ?>
            <?php if($product->has('documents')) : ?>
                <li><a href="#documents" data-toggle="tab">Documents</a></li>
            <?php endif; ?>
        </ul>
        <div class="tab-content">
            <?php if($product->has('options')) : ?>
                <div class="boundary tab-pane" id="options">
                    <?php foreach($product->getOptions() as $option) : ?>
                        <?php echo $this->partial($pdir . 'option.phtml', array('option' => $option, 'tree' => '[options]')); ?>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
            <?php if($product->has('specs')) : ?>
                <div class="boundary tab-pane" id="specs">
                    <?php foreach($product->getSpecs() as $spec) : ?>
                        <?php echo $this->partial($pdir . 'spec.phtml', array('spec' => $spec)); ?>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
            <?php if($product->has('documents')) : ?>
                <div class="boundary tab-pane" id="documents">
                    <?php foreach($product->getDocuments() as $document) : ?>
                        <?php echo $this->partial($pdir . 'document.phtml', array('document' => $document)); ?>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
        </div><hr/>
    </div>
    <script>
        $(document).ready(function(){
            $('.tab-content').children().first().addClass('active')
            $('.nav-tabs').children().first().addClass('active')
        });
    </script>
<?php endif; ?>

    <div class="span12 row">
        <?php echo  $this->speckCatalogUomsToCart($product->getUoms()); ?>
    </div>

</form>
