<?php $pdir = '/speck-catalog/product/option/'; ?>
<?php if($option->has('choices')): ?>
    <div class="option" style="margin-left:25px; border:1px solid #ddd; margin-bottom:5px; margin-right:25px; padding:10px">
        <strong><?php echo $option; ?><?php echo ($option->getRequired() ? '*' : ''); ?>:</strong><br/>
        <?php if ($option->has('instruction')):?>&nbsp;&nbsp;&nbsp;(<?php echo $option->getInstruction();?>)<br/><?php endif; ?>
        <?php $listType = $option->getOptionTypeId(); ?>
        <?php if ('1' === $listType): ?>
            <?php echo $this->partial($pdir . 'select.phtml', array('option' => $option)); ?>
        <?php elseif ('2' === $listType): ?>
            <?php echo $this->partial($pdir . 'radio.phtml', array('option' => $option)); ?>
        <?php elseif ('3' === $listType): ?>
            <?php echo $this->partial($pdir . 'checkbox.phtml', array('option' => $option)); ?>
        <?php endif; ?>
    </div>
<?php endif; ?>
