<div style="row" class="span12">
    <div class="span3">
        <?php echo  $this->formLabel($form->get('uom')); ?>
    </div>
    <div class="span1">
        <?php echo  $this->formLabel($form->get('quantity')); ?>
    </div>
    <div class="span2" style="align:bottom">
        &nbsp;<br/>
    </div>
</div>
<div style="row" class="span12">
    <div class="span3">
        <?php echo  $this->formSelect($form->get('uom')); ?>
    </div>
    <div class="span1">
        <?php echo  $this->formInput($form->get('quantity')->setAttribute('class', 'span1')); ?>
    </div>
    <div class="span2" style="align:bottom">
        <?php $submit = $form->get('submit'); ?>
        <?php $class = $submit->getAttribute('class') . ' span2'; ?>
        <?php echo  $this->formButton($submit->setAttribute('class', $class)); ?>
    </div>
</div>
