<div class="span2">
    <?php echo $uomTranslated; ?>
</div>
<div class="span1">
    $ <?php echo  number_format($uom->getPrice(), 2); ?>
</div>
<div class="span1">
    <?php echo $this->formInput($form->get('quantity')->setAttribute('class', 'span1')); ?>
</div>
<div class="span2">
    <?php $submit = $form->get('submit'); ?>
    <?php $class = $submit->getAttribute('class') . ' span2'; ?>
    <?php echo  $this->formButton($submit->setAttribute('class', $class)); ?>
</div>
