<?php
    $currentItem = $products->getCurrentItemCount();
    $lastItem    = ($products->getCurrentItemCount() + $products->getItemCountPerPage() < $products->getTotalItemCount())
                 ? $products->getCurrentItemCount() + $products->getItemCountPerPage()
                 : $products->getTotalItemCount();
    $page        = $products->getCurrentPageNumber();
    $pageCount   = ceil($products->getTotalItemCount() / $products->getItemCountPerPage());
    $nextPage    = ($page < $pageCount) ? $page + 1 : $page;
    $prevPage    = ($page - 1 > 1) ? $page - 1 : $page;
    $url         = 'zfcadmin/catalogmanager/products';
    $opts        = array();
    if ($this->query) {
        $opts['query'] = 'query=' . $this->query;
    }
    $opts['p']   = 'p=' . $prevPage;
    $prevUrl     = $this->url($url) . '?' . implode('&', $opts);
    $opts['p']   = 'p=' . $nextPage;
    $nextUrl     = $this->url($url) . '?' . implode('&', $opts);

    $paginator   = "Page {$page} of {$pageCount} <a href=\"{$prevUrl}\">Prev</a> | <a href=\"{$nextUrl}\">Next</a>";
?>


<div class="row-fluid">
    <div class="span2">
        <a href="<?php echo $this->url('zfcadmin/catalogmanager/new-product'); ?>" class="btn">New Product</a>
    </div>
    <div class="span2">
        <form method="GET">
        <input type="text" name="query" placeholder="Search Products" value="<?php echo $this->query;?>"/>
        </form>
    </div>

</div>
    <hr/>
<div class="row-fluid">
    <?php echo $paginator; ?>
        <div class="row-fluid" style="font-weight:bold">
            <div class="span1">Product Id</div><div class="span1">Type</div><div class="span4">Name</div>
        </div>
    <?php foreach($products as $product) : ?>
        <div class="row-fluid">
            <div class="span1">
                <b><?php echo $product->getProductId(); ?></b>
            </div>
            <div class="span1">
                <?php echo ($product->getProductTypeId() === 1) ? '(Shell) ' : '(Product)'; ?>
            </div>
            <div class="span7">
                <a href="/admin/catalogmanager/product/<?php echo $product->getProductId();?>"><?php echo $product;?></a>
            </div>
        </div>
    <?php endforeach; ?>
    <?php echo $paginator; ?>

</div>
