<?php $pdir = '/speck-catalog/catalog-manager/partial/'; ?>
<?php $formHelper = $this->speckCatalogForm($product, 'product'); ?>
<?php $parentKeyFields = $formHelper->getKeyFields(); ?>

<a href="/<?php echo $product->getProductId();?>">View this product</a><br/><br/>
<div class="tabbable">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#product" data-toggle="tab">Product</a></li>
        <li><a href="#options" data-toggle="tab">Option Groups</a></li>
      <?php if ($product->getProductTypeId() == 1) : ?>
        <li><a href="#builder" data-toggle="tab">Builder</a></li>
      <?php endif; ?>
        <li><a href="#specs" data-toggle="tab">Specs</a></li>
        <li><a href="#documents" data-toggle="tab">Documents</a></li>
        <li><a href="#images" data-toggle="tab">Images</a></li>
    </ul>

    <div class="tab-content">

        <?php echo  $this->render($pdir . 'product'); ?>

        <div id="options" class="tab-pane boundary">
            <div class="list-wrap">
                <div class="child-expand list-items-helper">
                    <div class="collapse-all"><i class="icon-arrow-up"></i></div>
                    <div class="expand-all"><i class="icon-arrow-down"></i></div>
                </div>
                <div class="list-items" data-type="option" data-parent="product" data-parent_key="<?php echo  $product->getKey();?>">
                    <?php echo  $this->speckCatalogRenderChildren('option', $product->getOptions()); ?>
                </div>
                <div class="row list-items-helper">
                    <?php echo  $this->speckCatalogAdderHelper()->addNew('option', 'product', $parentKeyFields); ?>
                </div>
            </div>
        </div>

      <?php if ($product->getProductTypeId() == 1) : ?>
        <div id="builder" class="tab-pane boundary">
            <div class="list-wrap">
                <div class="child-expand list-items-helper">
                    <div class="collapse-all"><i class="icon-arrow-up"></i></div>
                    <div class="expand-all"><i class="icon-arrow-down"></i></div>
                </div>
                <div class="list-items" data-type="product" data-parent="product" data-parent_key="<?php echo  $product->getKey();?>">
                    <?php echo  $this->speckCatalogRenderChildren('builder_product', $product->getBuilders()); ?>
                </div>
                <div class="row list-items-helper">
                    <?php echo  $this->speckCatalogAdderHelper()->find('builder_product', 'product', $parentKeyFields); ?>
                </div>
            </div>
        </div>
      <?php endif; ?>

        <div id="specs" class="tab-pane boundary">
            <div class="list-wrap">
                <div class="list-items">
                    <?php echo  $this->speckCatalogRenderChildren('spec', $product->getSpecs()); ?>
                </div>
                <div class="row list-items-helper">
                    <?php echo  $this->speckCatalogAdderHelper()->addNew('spec', 'product', $parentKeyFields); ?>
                </div>
            </div>
        </div>

        <div id="documents" class="tab-pane boundary">
            <div class="list-wrap">
                <div class="list-items" type="document" parent="product">
                    <?php echo  $this->speckCatalogRenderChildren('document', $product->getDocuments()); ?>
                </div>
                <div class="row list-items-helper">
                    <div class="span5">
                        <?php echo  $this->speckCatalogProductDocumentUploader($parentKeyFields); ?>
                    </div>
                </div>
            </div>
        </div>

        <div id="images" class="tab-pane boundary">
            <div class="list-wrap">
                <div class="list-items" type="image" parent="product">
                    <?php echo $this->speckCatalogRenderChildren('product_image', $product->getImages()); ?>
                </div>
                <div class="row list-items-helper">
                    <div class="span5">
                        <?php echo  $this->speckCatalogProductImageUploader($parentKeyFields); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div><!--/tabbable-->

<?php echo $this->render($pdir.'modal.phtml'); ?>
