<?php if(isset($results)) : ?>
    <?php foreach($results as $entity) : ?>
        <?php $class = explode('\\', get_class($entity)); $className = array_pop($class);?>
        <?php $method = 'get'.ucfirst($className).'Id'; ?>
        <?php $entityId = $entity->$method(); ?>
        <?php $title = ''; ?>
        <?php foreach($entity->toArray() as $key => $val){$title.="| {$key}: {$val} |";}; ?>
        <?php echo $className;?> - <a href="/admin/catalogmanager/<?php echo strtolower($className);?>?id=<?php echo $entityId;?>" data-content="<?php echo $title;?>" rel="popover" data-placement="below">"<?php echo $entity;?>"</a><br/>

    <?php endforeach; ?>

<?php else: ?>
    No Results
<?php endif; ?>
