<?php if($results) : ?>
    <table class="table table-condensed">
        <thead><td>type</td><td>description</td></thead> 
        <tbody>

            <?php foreach($results as $model) : ?>

                <?php 
                    $class = explode('\\', get_class($model)); $className = array_pop($class);
                    $getModelId = 'get'.$className.'Id';
                    $entityId = $model->$getModelId();
                ?>

                <tr>
                    <td><?php echo $className;?></td>
                    <td>
                        <form action="" class="search-result-data">
                            <input type="hidden" name="id"                value="<?php echo $entityId;?>"                  />
                            <input type="hidden" name="class_name"        value="<?php echo $data['class_name'];?>"        />
                            <input type="hidden" name="parent_id"         value="<?php echo $data['parent_id'];?>"         />
                            <input type="hidden" name="parent_class_name" value="<?php echo $data['parent_class_name'];?>" />
                            <input type="hidden" name="child_id"          value="<?php echo $entityId;?>"                  />
                            <input type="hidden" name="child_class_name"  value="<?php echo $data['child_class_name'];?>"  />
                            <input type="hidden" name="new_class_name"    value="<?php echo $data['new_class_name'];?>"    />
                            <input type="hidden" name="partial_name"      value="<?php echo $data['partial_name'];?>"      />
                                
                            <a href="" class="search-result">"<?php echo $model;?>"</a>
                        </form>
                    </td>
                </tr>

            <?php endforeach; ?>

        </tbody>
    </table>
<?php else : ?>
    no results
<?php endif; ?>
