<?php if(is_array($message)) : ?>
  <div class="alert-message <?php echo $message['type'];?>">
    <a class="close" href="#">×</a>
    <p>
        <?php if(isset($message['status'])) : ?><strong><?php echo $message['status'];?></strong><?php endif; ?>
        <?php if(isset($message['message'])) : ?><?php echo $message['message'];?><?php endif; ?>
        <?php if(isset($message['url'])) : ?><a href="<?php echo $message['url'];?>"><?php echo $message['url'];?></a><?php endif; ?>
    </p>
  </div>
<?php else : ?>
  <div class="alert-message">
    <a class="close" href="#">×</a>
    <p><?php echo $message;?></p>
  </div>  
<?php endif; ?>
