<?php
$product = $builderProduct['product'];

$parentProductKeyFields = array('product_id' => $builderProduct['parent_product_id']);
$builderKeyFields = array('product_id' => $builderProduct['product_id']);

$formHelper = $this->speckCatalogForm(null, 'builder_product');
$formHelper->getForm()->setData($builderProduct);
?>

<div id="" class="builder contrastbg boundary shadow">
    <div class="entity-header">
        <div class="collapser left"><i class="icon-chevron-down"></i></div>
        <div class="title sort-handle collapser left">&nbsp; <?php echo $product->__toString();?></div>
        <div class="remover right">
            <?php echo  $this->speckCatalogAdderHelper()->removeChild('product', $parentProductKeyFields, 'builder', $builderKeyFields); ?>
        </div>
    </div>
    <div class="entity-content">

        <?php echo $formHelper->renderForm();?>

    </div>
</div>
