<?php foreach ($children as $child) : ?>
    <?php if($type === 'product') : ?>
        <div class="tree-product">
            <div class="tree-product-title title"><b>:P: </b><?php echo  $child ;?></div>
        </div>
    <?php else : ?>
        <div class="tree-cat">
            <div class="tree-cat-title title"><b>:C: </b><?php echo  $child ;?></div>
            <div class="tree-cat-cats cat-sort"></div>
            <div class="tree-cat-products product-sort"></div>
        </div>
    <?php endif; ?>
<?php endforeach; ?>
