<?php
    $parentOptionKeyFields = $this->SpeckCatalogForm($choice->getParent(), 'option')->getKeyFields();
    $formHelper = $this->speckCatalogForm($choice, 'choice');
    $keyFields = $formHelper->getKeyFields();
?>
<div class="choice whitebg boundary shadow" id="<?php echo  $choice->getKey(); ?>" >
    <div class="entity-header">
        <div class="collapser left"><i class="icon-chevron-down initialCollapse"></i></div>
        <?php if($choice->has('parentOptions')) : ?>
            <div class="left"><i class="icon-eye-open" title="This choice is shared <?php echo count($choice->getParentOptions());?> times"></i></div>
        <?php endif; ?>
        <?php if ($choice->has('options')) : ?>
            <div class="left"><span class="icon-list" title="has options"></span></div>
        <?php elseif($choice->has('product')) : ?>
            <div class="left"><span class="icon-tag"></span></div>
        <?php endif; ?>
        <div class="title sort-handle collapser left">&nbsp; <?php echo $choice;?></div>
        <div class="remover right">
            <?php echo  $this->speckCatalogAdderHelper()->removeChild('option', $parentOptionKeyFields, 'choice', $keyFields); ?>
        </div>
    </div>
    <div class="entity-content">
        <?php echo $formHelper->renderForm(); ?>
        <?php if($choice->has('product')) : ?>
            <?php echo $this->speckCatalogRenderChildren('product', array($choice->getProduct()));?>
        <?php else: ?>
            <div class="list-wrap half-pad">
                <div class="child-expand list-items-helper">
                <div class="collapse-all"><i class="icon-arrow-up"></i></div>
                <div class="expand-all"><i class="icon-arrow-down"></i></div>
                    <span class="smallcaps">&nbsp;option groups</span><br/>
                </div>
                <div class="list-items" data-type="option" data-parent="choice" data-parent_key="<?php echo  $choice->getKey(); ?>">
                    <?php echo $this->speckCatalogRenderChildren('option', $choice->getOptions());?>
                </div>
                <div class="row list-items-helper">
                    <?php echo $this->speckCatalogAdderHelper()->addNew('option', 'choice', $keyFields); ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
