<table class='bordered-table'>
    <thead>
        <tr><th>Entity</th><th></th></tr>
    </thead>
    <tbody>
        <?php if (count($paginator)): ?>
            <?php foreach ($paginator as $i => $item): ?>
                <?php $class = explode('\\', get_class($item)); $className = array_pop($class);  ?>
                <tr>
                    <td><?php echo $className;?></td>
                    <td><a href="/admin/catalogmanager/<?php echo strtolower($className);?>?entityId=<?php echo $i;?>&parent_id=<?php echo $parentId;?>"><?php echo $item;?></a></td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
    </tbody>
</table>
<?php if(count($paginator) > 1) :?>
    <?php echo $paginator->setView($this);?>
<?php endif; ?>
