<form method="POST" class="search">
    <?php foreach ($fields as $key => $val) : ?>
        <?php if(is_array($val)) : ?>
            <?php foreach($val as $key2 => $val2) : ?>
                <input type="hidden" name="<?php echo $key;?>[<?php echo $key2;?>]" value="<?php echo $val2;?>" />
            <?php endforeach;?>
        <?php else: ?>
            <input type="hidden" name="<?php echo $key;?>" value="<?php echo $val;?>" />
        <?php endif; ?>
    <?php endforeach; ?>
    <input type="text" name="query"></input>
</form>

<?php if(count($models)) : ?>
    <form method="POST" class="found">
        <?php foreach ($fields as $key => $val) : ?>
            <?php if(is_array($val)) : ?>
                <?php foreach($val as $key2 => $val2) : ?>
                    <input type="hidden" name="<?php echo $key;?>[<?php echo $key2;?>]" value="<?php echo $val2;?>" />
                <?php endforeach;?>
            <?php else: ?>
                <input type="hidden" name="<?php echo $key;?>" value="<?php echo $val;?>" />
            <?php endif; ?>
        <?php endforeach; ?>
        <?php $n=0; ?>
        <?php foreach($models as $model) : ?>
            <?php $n++; ?>
            <?php $fields = $this->speckCatalogForm($model, 'product')->getKeyFields();?>
            <?php foreach($fields as $key => $val): ?>
                <input type="hidden" name="<?php echo $key;?>[<?php echo $n;?>]" value="<?php echo $val;?>" />
            <?php endforeach;?>
            <input type="checkbox" name="check[<?php echo $model->getProductId();?>]" value="1">&nbsp;<?php echo $model;?></input><br/>
        <?php endforeach; ?>
        <input type="submit">
    </form>
<?php endif; ?>
