<?php $pdir = '/catalog/catalog-manager/partial/'; ?>

<?php if(isset($collapse)){ $collapse='initialCollapse';} else { $collapse='';} ?>
<div class="boundary whitebg shadow" id="" >
    <div class="entity-header">
        <div class="collapser"><i class="icon-chevron-down <?php echo $collapse;?>"></i></div>
        <div class="remover"><div class="hide"><span class="icon-remove" title="double click to remove"></span></div></div>
        <div><i class="icon-picture"></i></div>
        <div class="title sort-handle collapser">&nbsp; <?php echo $optionImage;?></div>
    </div>
    <div class="entity-content initialcol">
        <?php echo $this->partial($pdir.'form/image.phtml', array('image' => $optionImage));?>
    </div>
</div>
