<?php $pdir = '/speck-catalog/catalog-manager/partial/'; ?>
<?php $collapse = isset($collapse) ? 'initialCollapse' : ''; ?>

<div class="boundary contrastbg shadow" id="" >
    <div class="entity-header">
        <div class="collapser left"><i class="icon-chevron-down <?php echo $collapse;?>"></i></div>
        <div class="left"><i class="icon-picture"></i></div>
        <div class="title sort-handle collapser left">&nbsp; <?php echo $productImage;?></div>
    </div>
    <div class="entity-content initialcol">
        <?php echo $this->partial($pdir.'form/image.phtml', array('image' => $productImage));?>
    </div>
</div>
